parameters:
#    m_so_rss_reader.example.class: MSo\RssReaderBundle\Example

services:
#    m_so_rss_reader.example:
#        class: %m_so_rss_reader.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
